name: Build Extension

on:
  push:
    branches: [ main, ci-sandbox ]
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
  pull_request: 
    branches: [ '**' ]

jobs:
  extension-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Runs javascript to extract push events from both tags and branch (only main, due to workflow trigger)
      # converts refs/<>/<name> -> <name>
      # eg:
      #     refs/head/main   -> main
      #     refs/tags/v0.1.0 -> v0.1.0
      #
      - name: Set outputs
        id: sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      # Patches the BERGAMOT_VERSION file used by sphinx-docs at run time to
      # obtain names like 'main' or 'ci-sandbox' to not confuse with version
      # based documentation built separately.
      - name: Deploy-time patch version 
        run: | 
            echo ${{ steps.sha.outputs.sha_short }} 

      - name: Set up dependencies
        run: |
            sudo apt-get install -y doxygen nodejs
            npm install --global yarn

      - name: Install yarn requirements
        run: |
            yarn install --frozen-lockfile
            yarn bergamot-translator:download-and-import
            # TODO: Setup Checks
            yarn ci:install-firefox:linux
            # Don't need telemetry.
            
      - name: Build Extension Firefox Infobar UI
        run: |
            yarn build:firefox-infobar-ui

      - name: Build Extension Firefox Cross Browser UI
        run: |
            yarn build:cross-browser-ui:firefox

      - name: Build Extension Chrome Cross Browser UI
        run: |
            yarn build:cross-browser-ui:chrome

      - name: Upload Extension Firefox Infobar UI
        uses: actions/upload-artifact@v2
        with:
          name: bergamot-browser-extension-${{ steps.sha.outputs.sha_short }}.xpi
          path: dist/production/firefox/firefox-infobar-ui/firefox-translations-0.4.4.xpi
          if-no-files-found: error

      - name: Upload Extension Firefox Cross Browser UI
        uses: actions/upload-artifact@v2
        with:
          name: bergamot-browser-extension-${{ steps.sha.outputs.sha_short }}-cross-browser-ui.xpi
          path: dist/production/firefox/cross-browser-ui/bergamot-browser-extension-0.4.4-firefox-cross-browser-ui.xpi
          if-no-files-found: error

      - name: Upload Extension Chrome Cross Browser UI
        uses: actions/upload-artifact@v2
        with:
          name: bergamot-browser-extension-${{ steps.sha.outputs.sha_short }}-chrome.zip
          path: dist/production/chrome/cross-browser-ui/bergamot-browser-extension-0.4.4-chrome-cross-browser-ui.zip
          if-no-files-found: error

